version: '3.9'

volumes:
  static_volume:
  media_volume:

services:
  web:
    build: ./compose/back/
    volumes:
      - ./compose/back/kelechek_kooperativ/:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.venv/.env.dev
    image: web:django
    container_name: django_container
    command: gunicorn --bind 0.0.0.0:8000 kelechek_project.wsgi --workers=4
    depends_on:
      - db
    networks:
      - django-network
  db:
    image: postgres:13-alpine
    volumes:
      - ./compose/data/db:/var/lib/postgresql/data
      - ./compose/postgres/maintenance:/usr/local/bin/maintenance
    restart: always
    env_file:
      - ./.venv/.env.dev
    container_name: postgres_container
    networks:
      - django-network
  nginx:
    build: ./compose/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./compose/nginx/conf:/etc/letsencrypt
      - ./compose/nginx/:/app/certbot
    links:
      - web
    depends_on:
      - web
    networks:
      - django-network

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./compose/nginx/conf:/etc/letsencrypt
      - ./compose/nginx/:/app/certbot

networks:
  django-network:
    name: django-network